import pandas as pd

# Human-readable names for classification metrics.
CLASSIFICATION_METRIC_NAMES = {
    "ap": "AP",
    "roc_auc": "AUC-ROC",
    "soft_precision": "SP",
    "soft_recall_huang_tagare": "SR (HT)",
    "soft_recall_inlier_avg": "SR (IA)",
    "soft_recall_global_avg": "SR (GA)",
}

# Human-readable names for reconstruction metrics.
RECONSTRUCTION_METRIC_NAMES = {
    "rmse": "RMSE",
    "pearson_corr": "Correlation",
    "gt_frc_resolution": "Ground Truth FRC Resolution",
    "hs_frc_resolution": "Half-Set FRC Resolution",
}


def format_column_name(name: str) -> str:
    """
    Convert internal dataframe column names into presentation-friendly labels.

    Known metric names are mapped to predefined abbreviations or labels.
    Unknown names are converted by capitalizing and replacing underscores
    with spaces.

    Parameters
    ----------
    name : str
        Original dataframe column name.

    Returns
    -------
    str
        Formatted column name suitable for display in LaTeX tables.
    """
    if name in CLASSIFICATION_METRIC_NAMES:
        return CLASSIFICATION_METRIC_NAMES[name]

    if name in RECONSTRUCTION_METRIC_NAMES:
        return RECONSTRUCTION_METRIC_NAMES[name]

    return name.capitalize().replace("_", " ")


def move_caption_to_bottom(latex: str, caption: str) -> str:
    """
    Move a LaTeX table caption below the tabular environment.

    Pandas generates captions above tables by default. This helper
    relocates the caption to the bottom of the table environment.

    Parameters
    ----------
    latex : str
        LaTeX table string generated by pandas.
    caption : str
        Caption text used in the table.

    Returns
    -------
    str
        Modified LaTeX table with the caption below the tabular block.
    """
    caption_text = f"\\caption{{{caption}}}"

    # Remove the original caption.
    latex = latex.replace(caption_text, "")

    # Reinsert the caption after the tabular environment.
    latex = latex.replace("\\end{tabular}", "\\end{tabular}\n" + caption_text)

    return latex


def format_dataframe(
    df: pd.DataFrame,
    caption: str | None = None,
    label: str | None = None,
    float_precision: int = 3,
) -> str:
    """
    Convert a dataframe into a formatted LaTeX table.

    The formatting process includes:
    - Renaming columns into presentation-friendly labels
    - Replacing underscores with spaces in string columns
    - Hiding the dataframe index
    - Formatting floating-point precision
    - Centering the table
    - Optionally adding captions and labels

    Parameters
    ----------
    df : pd.DataFrame
        Input dataframe.
    caption : str | None, optional
        Table caption.
    label : str | None, optional
        LaTeX label used for references.
    float_precision : int, optional
        Number of decimal places for floating-point values.

    Returns
    -------
    str
        Formatted LaTeX table string.
    """
    # Rename columns into display-friendly labels.
    formatted_df = df.rename(columns=format_column_name).copy()

    # Replace underscores with spaces in string-valued columns.
    string_columns = formatted_df.select_dtypes(include=["object", "string"]).columns

    formatted_df[string_columns] = formatted_df[string_columns].apply(
        lambda col: col.str.replace("_", " ", regex=False)
    )

    # Create a Styler object for LaTeX rendering.
    styler = formatted_df.style.hide(axis="index").format(precision=float_precision)

    latex = styler.to_latex(
        hrules=True,
        position="H",
        position_float="centering",
        caption=caption,
        label=label,
    )

    # Pandas emits captions above tables by default.
    # Move them below the table if requested.
    if caption:
        latex = move_caption_to_bottom(latex, caption)

    return latex
