from pathlib import Path
from typing import Any, Iterable

import pandas as pd

from method_comparison.domain.enums import Space, AggregationStrategy
from method_comparison.domain.reports import EvaluationReport
from method_comparison.visualization.plotting import (
    AVERAGE_NAME,
    save_snr_reports_figures,
    produce_snr_classification_figures,
    plot_vs_snr,
)

# Required LaTeX packages for rendering tables and formatting the document.
LATEX_PACKAGES = ["booktabs", "float", "caption", "graphicx"]

# Human-readable names for classification metrics.
CLASSIFICATION_METRIC_NAMES = {
    "ap": "AP",
    "soft_precision": "SP",
    "soft_recall_huang_tagare": "SR (HT)",
    "soft_recall_inlier_avg": "SR (IA)",
    "soft_recall_global_avg": "SR (GA)",
}

# Human-readable names for reconstruction metrics.
RECONSTRUCTION_METRIC_NAMES = {
    "rmse": "RMSE",
    "pearson_corr": "Correlation",
    "fsc_resolution": "Resolution",
}


def generate_document_preamble() -> str:
    """
    Generate the LaTeX preamble required for the report.

    The generated preamble includes:
    - Document class declaration
    - Required LaTeX packages
    - Page geometry configuration
    - Table caption positioning

    Returns
    -------
    str
        LaTeX preamble string.
    """
    s = "\\documentclass{article}\n\n"

    # Add all necessary packages
    for package in LATEX_PACKAGES:
        s += f"\\usepackage{{{package}}}\n"

    # Configure page geometry (margin)
    s += "\\usepackage[margin=3cm]{geometry}\n"

    # Configure table captions to appear below tables.
    s += "\n\\captionsetup[table]{position=bottom}\n"

    return s


def format_column_name(name: str) -> str:
    """
    Convert internal dataframe column names into presentation-friendly labels.

    Known metric names are mapped to predefined abbreviations or labels.
    Unknown names are converted by capitalizing and replacing underscores
    with spaces.

    Parameters
    ----------
    name : str
        Original dataframe column name.

    Returns
    -------
    str
        Formatted column name suitable for display in LaTeX tables.
    """
    if name in CLASSIFICATION_METRIC_NAMES:
        return CLASSIFICATION_METRIC_NAMES[name]

    if name in RECONSTRUCTION_METRIC_NAMES:
        return RECONSTRUCTION_METRIC_NAMES[name]

    return name.capitalize().replace("_", " ")


def move_caption_to_bottom(latex: str, caption: str) -> str:
    """
    Move a LaTeX table caption below the tabular environment.

    Pandas generates captions above tables by default. This helper
    relocates the caption to the bottom of the table environment.

    Parameters
    ----------
    latex : str
        LaTeX table string generated by pandas.
    caption : str
        Caption text used in the table.

    Returns
    -------
    str
        Modified LaTeX table with the caption below the tabular block.
    """
    caption_text = f"\\caption{{{caption}}}"

    # Remove the original caption.
    latex = latex.replace(caption_text, "")

    # Reinsert the caption after the tabular environment.
    latex = latex.replace("\\end{tabular}", "\\end{tabular}\n" + caption_text)

    return latex


def format_dataframe(
    df: pd.DataFrame,
    caption: str | None = None,
    label: str | None = None,
    float_precision: int = 3,
) -> str:
    """
    Convert a dataframe into a formatted LaTeX table.

    The formatting process includes:
    - Renaming columns into presentation-friendly labels
    - Replacing underscores with spaces in string columns
    - Hiding the dataframe index
    - Formatting floating-point precision
    - Centering the table
    - Optionally adding captions and labels

    Parameters
    ----------
    df : pd.DataFrame
        Input dataframe.
    caption : str | None, optional
        Table caption.
    label : str | None, optional
        LaTeX label used for references.
    float_precision : int, optional
        Number of decimal places for floating-point values.

    Returns
    -------
    str
        Formatted LaTeX table string.
    """
    # Rename columns into display-friendly labels.
    formatted_df = df.rename(columns=format_column_name).copy()

    # Replace underscores with spaces in string-valued columns.
    string_columns = formatted_df.select_dtypes(include=["object", "string"]).columns

    formatted_df[string_columns] = formatted_df[string_columns].apply(
        lambda col: col.str.replace("_", " ", regex=False)
    )

    # Create a Styler object for LaTeX rendering.
    styler = formatted_df.style.hide(axis="index").format(precision=float_precision)

    latex = styler.to_latex(
        hrules=True,
        position="H",
        position_float="centering",
        caption=caption,
        label=label,
    )

    # Pandas emits captions above tables by default.
    # Move them below the table if requested.
    if caption:
        latex = move_caption_to_bottom(latex, caption)

    return latex


def write_experiment_info(cfg: dict[str, Any], snr_list: Iterable[float]) -> str:
    """
    Generate a LaTeX summary of the experiment configuration.

    Produces an itemized list of image generation parameters and the
    SNR levels used in the experiment.

    Parameters
    ----------
    cfg : dict[str, Any]
        Full experiment configuration dict. Must contain a ``"generation"``
        sub-dict with keys: ``n_copies``, ``n_copies_rotated``,
        ``n_misclassified``, ``max_rotation_reference``,
        ``min_rotation_very_rotated``, and ``max_rotation_very_rotated``.
    snr_list : Iterable[float]
        SNR values tested in the experiment.

    Returns
    -------
    str
        LaTeX-formatted experiment summary block.
    """
    generation_cfg = cfg["generation"]
    text = ""

    text += "\n\\textbf{Image generation parameters:}\n"
    text += "\n\\begin{itemize}\n"

    text += f"\t\\item Number of good copies of reference: ${generation_cfg["n_copies"]}$.\n"
    text += f"\t\\item Number of badly misaligned images: ${generation_cfg["n_copies_rotated"]}$.\n"
    text += f"\t\\item Number of misclassified images: ${generation_cfg["n_misclassified"]}$.\n"
    text += f"\t\\item Max rotation of good copies: $\\pm {generation_cfg["max_rotation_reference"]:.2f}$ degrees.\n"
    text += f"\t\\item Maximum rotation of misaligned images: ${generation_cfg["max_rotation_very_rotated"]:.2f}$ degrees.\n"
    text += f"\t\\item Minimum rotation of misaligned images: ${generation_cfg["min_rotation_very_rotated"]:.2f}$ degrees.\n"

    text += "\n\\end{itemize}\n"

    text += "\n\\textbf{Signal-to-noise ratios tested:} "
    text += ", ".join([f"{snr:.3f}" for snr in snr_list])
    text += "\n"

    return text


def create_reconstruction_table(
    report: EvaluationReport, caption: str = "Reconstruction metrics for each method"
) -> str:
    """
    Generate the reconstruction metrics section of the report.

    Parameters
    ----------
    report : EvaluationReport
        Evaluation report containing reconstruction metrics.

    Returns
    -------
    str
        LaTeX-formatted reconstruction metrics table.
    """
    reconstruction_df = report.reconstruction_metrics_dataframe()

    return format_dataframe(
        reconstruction_df,
        caption=caption,
    )


def generate_reconstruction_section(
    snr_reports: dict[float, EvaluationReport],
    output_path: Path,
    figures_path: Path,
    dpi: int = 150,
) -> str:
    """
    Generate the reconstruction metrics section of the LaTeX report.

    Produces one subsection per SNR level with a formatted metrics table,
    followed by a 'metrics vs. SNR' subsection containing plots for RMSE,
    Pearson correlation, and FRC resolution.

    Parameters
    ----------
    snr_reports : dict[float, EvaluationReport]
        Dict mapping every SNR level to its evaluation report.
    output_path : Path
        Path to the directory where ``report.tex`` will be generated.
        Used to compute relative figure paths.
    figures_path : Path
        Directory where generated figure files will be saved.
    dpi : int, optional
        Resolution for saved figures, by default 150.

    Returns
    -------
    str
        LaTeX text for the reconstruction section, ready to be written
        into the document.
    """
    text = "\n\\section{Reconstruction metrics}\n"

    reconstruction_dfs: dict[float, pd.DataFrame] = {}
    for snr, report in snr_reports.items():
        text += f"\n\\subsection{{SNR {snr:.3f}}}\n"
        text += create_reconstruction_table(
            report, caption=f"Reconstruction metrics for each method at SNR {snr:.3f}"
        )

        df = report.reconstruction_metrics_dataframe()
        df["snr"] = snr
        reconstruction_dfs[snr] = df

    overall_rec_df = pd.concat(reconstruction_dfs.values())

    text += "\n\\subsection{Reconstruction metrics vs. SNR graphs}\n"

    snr_vs_rmse_plot = plot_vs_snr(
        df=overall_rec_df,
        metrics=["rmse"],
        save_path=figures_path / "snr_vs_rmse.pdf",
        metric_labels=["RMSE"],
        dpi=dpi,
        title="RMSE vs SNR",
        ylabel="RMSE",
    ).relative_to(output_path)

    text += "\n\\textbf{RMSE}\n"
    text += generate_figures_section(
        [snr_vs_rmse_plot], "Reconstruction metrics vs SNR: RMSE"
    )

    snr_vs_corr_plot = plot_vs_snr(
        df=overall_rec_df,
        metrics=["pearson_corr"],
        save_path=figures_path / "snr_vs_corr.pdf",
        metric_labels=["Correlation"],
        dpi=dpi,
        title="Reconstruction correlation vs SNR",
        ylabel="Correlation",
    ).relative_to(output_path)

    text += "\n\\textbf{Correlation}\n"
    text += generate_figures_section(
        [snr_vs_corr_plot], "Reconstruction metrics vs SNR: correlation"
    )

    snr_vs_frc_plot = plot_vs_snr(
        df=overall_rec_df,
        metrics=["fsc_resolution"],
        save_path=figures_path / "snr_vs_frc.pdf",
        metric_labels=["FRC Resolution"],
        dpi=dpi,
        title="Reconstruction resolution vs SNR",
        ylabel="Frequency",
    ).relative_to(output_path)

    text += "\n\\textbf{FRC Resolution}\n"
    text += generate_figures_section(
        [snr_vs_frc_plot], "Reconstruction metrics vs SNR: FRC resolution"
    )

    return text


def get_classification_table(
    classification_df: pd.DataFrame, space: Space, strategy: AggregationStrategy
) -> pd.DataFrame | None:
    """
    Extract a classification metrics sub-table for a given space and strategy.

    Filters ``classification_df`` to rows matching ``space`` and
    ``strategy``, and returns ``None`` when the result would be empty or
    consist solely of the baseline average method.

    Parameters
    ----------
    classification_df : pd.DataFrame
        Full classification metrics dataframe from
        ``EvaluationReport.classification_metrics_dataframe()``.
    space : Space
        Reconstruction space to filter on (matched against the ``"space"``
        column by name).
    strategy : AggregationStrategy
        Aggregation strategy to filter on (matched against the
        ``"aggregation_strategy"`` column by value).

    Returns
    -------
    pd.DataFrame | None
        Filtered dataframe, or ``None`` if no relevant rows exist.
    """
    space_rows = classification_df["space"] == space.name

    if not space_rows.any():
        return None

    space_df = classification_df[space_rows]

    # Skip sections containing only the baseline average method.
    if len(space_df.index) == 1 and space_df["method"].iloc[0] == AVERAGE_NAME:
        return None

    rows = space_df["aggregation_strategy"] == strategy.value

    if not rows.any():
        return None

    return space_df[rows]


def generate_classification_tables(report: EvaluationReport) -> str:
    """
    Generate the classification metrics section of the report for one SNR level.

    Tables are grouped by:
    - reconstruction space
    - aggregation strategy

    Empty groups and groups containing only the baseline average
    method are skipped.

    Parameters
    ----------
    report : EvaluationReport
        Evaluation report containing classification metrics.

    Returns
    -------
    str
        LaTeX-formatted classification section.
    """
    classification_df = report.classification_metrics_dataframe()
    text = ""

    for space in Space:
        if not (classification_df["space"] == space).any():
            continue

        text += f"\n\\subsubsection*{{{space.label}}}\n"

        for strategy in AggregationStrategy:
            df = get_classification_table(classification_df, space, strategy)
            if df is None:
                continue

            text += f"\n\\textbf{{{strategy.label}}}\n\n" "\\smallskip\n\n"

            # Remove grouping columns before rendering the table.
            df = df.drop(["space", "aggregation_strategy"], axis=1)

            text += format_dataframe(df)

    return text


def generate_classification_section(
    snr_reports: dict[float, EvaluationReport],
    output_path: Path,
    figures_path: Path,
    dpi: int = 150,
) -> str:
    """
    Generates the complete classification section of the report, including all SNR
    subsections and metrics-vs-snr plots.

    Parameters
    ----------
    snr_reports : dict[float, EvaluationReport]
        Dict mapping every SNR level to its evaluation report.
    output_path : Path
        Path to the directory where the `report.tex` will be generated.
    figures_path : Path
        Path to the directory where the figures will be saved
    dpi : int, optional
        Resolution for saved figures, by default 150.

    Returns
    -------
    str
        LaTeX text for the classification section of the report, ready to be written
        into the document. This section contains:
            - One subsection per SNR level. Each of these subsections has a
            classification metrics table per space and aggregation strategy where
            methods have been tested.
            - One 'metrics vs. SNR' section, containing a plot of soft precision
            and soft recall (calculated according to Huang and Tagare) vs. SNR.
    """
    text = "\n\\section{Classification metrics}\n"

    classification_dfs: dict[float, pd.DataFrame] = {}
    for snr, report in snr_reports.items():
        text += f"\n\\subsection{{SNR {snr:.3f}}}\n"
        text += "\n"
        text += generate_classification_tables(report)

        classification_dfs[snr] = report.classification_metrics_dataframe()
        classification_dfs[snr]["snr"] = snr

    overall_df = pd.concat(classification_dfs.values())

    precision_and_recall_curves = plot_vs_snr(
        overall_df,
        metrics=["soft_precision", "soft_recall_huang_tagare"],
        save_path=figures_path / "snr_vs_precision_recall.pdf",
        metric_labels=["Soft precision", "Soft recall"],
        dpi=dpi,
        title="Precision and recall vs SNR",
        ylabel="Score",
    ).relative_to(output_path)

    text += "\n\\textbf{Precision and recall curves}\n"
    text += generate_figures_section(
        [precision_and_recall_curves], "Classification metrics vs. SNR"
    )

    average_precision_curves = plot_vs_snr(
        overall_df,
        metrics="ap",
        save_path=figures_path / "snr_vs_average_precision.pdf",
        metric_labels="Average precision",
        dpi=dpi,
        title="Average precision vs SNR",
        ylabel="Average precision",
    ).relative_to(output_path)

    text += "\n\\textbf{Average precision curves}\n"
    text += generate_figures_section(
        [average_precision_curves], "Average precision vs. SNR"
    )

    return text


def generate_figures_section(figure_paths: list[Path], caption_prefix: str) -> str:
    """
    Generate a LaTeX block embedding a list of figures.

    Parameters
    ----------
    figure_paths : list[Path]
        Paths to the figure files to include.
    caption_prefix : str
        Prefix used in each figure caption, e.g. `"Weight distribution"`.

    Returns
    -------
    str
        LaTeX string containing one `figure` environment per path.
    """
    text = ""

    for i, path in enumerate(figure_paths, start=1):
        text += (
            f"\n\\begin{{figure}}[H]\n"
            f"  \\centering\n"
            f"  \\includegraphics[width=\\textwidth]{{{path.as_posix()}}}\n"
            f"  \\caption{{{caption_prefix} {i}}}\n"
            f"\\end{{figure}}\n"
        )

    return text


def diagnostic_plots_text(
    saved_figures: dict[str, list[Path]], output_path: Path
) -> str:
    """
    Generate a complete LaTeX plots subsection from saved figure paths.

    Parameters
    ----------
    saved_figures : dict[str, list[Path]]
        Mapping returned by `save_report_figures`, with keys
        `"weight_distributions"` and `"fsc_curves"`.
    output_path: Path
        Path to the directory that contains the `report.tex` file.

    Returns
    -------
    str
        LaTeX section string ready to be written into a document.
    """
    text = ""
    weight_paths = [
        p.relative_to(output_path)
        for p in saved_figures.get("weight_distributions", [])
    ]
    if weight_paths:
        text += "\n\\subsubsection{Weight Distributions}\n"
        text += generate_figures_section(weight_paths, "Weight distribution")

    fsc_paths = [
        p.relative_to(output_path) for p in saved_figures.get("fsc_curves", [])
    ]
    if fsc_paths:
        text += "\n\\subsubsection{FSC Curves}\n"
        text += generate_figures_section(fsc_paths, "FSC curves")

    return text


def generate_plots_section(
    snr_reports: dict[float, EvaluationReport],
    output_path: Path,
    figures_path: Path,
    plot_options: dict[str, Any],
) -> str:
    """
    Generates the LaTeX text for the plots section.

    Parameters
    ----------
    snr_reports : dict[float, EvaluationReport]
        Dict mapping every SNR level to its evaluation report
    output_path : Path
        Path to the directory where the `report.tex` will be generated.
    figures_path : Path
        Path to the directory where the figures will be saved.
    plot_options : dict[str, Any]
        Dict containing the following keyword arguments for the figure generation:
            - max_subplots: int
            - density: bool
            - dpi: int

    Returns
    -------
    str
        LaTeX text for the 'diagnostic plots' section. This section contains one
        subsection per SNR level. Each of these subsection contains:
            - Weight distribution histograms, for each method, space and aggregation strategy.
            - One plot representing the FRC curves for all methods.
    """
    plots = save_snr_reports_figures(
        snr_reports, output_path=figures_path, **plot_options
    )

    text = "\n\\section{Diagnostic plots}\n"

    for snr in snr_reports:
        text += f"\n\\subsection{{SNR {snr:.3f}}}\n"
        text += diagnostic_plots_text(saved_figures=plots[snr], output_path=output_path)

    return text


def generate_latex_report(
    snr_reports: dict[float, EvaluationReport],
    output_path: Path,
    cfg: dict[str, Any],
    plot_options: dict[str, Any],
) -> None:
    """
    Generate a complete LaTeX report document.

    The generated report contains:
    - Experiment configuration summary
    - Classification metrics section (tables and vs-SNR plots)
    - Reconstruction metrics section (tables and vs-SNR plots)
    - Diagnostic plots section (weight distributions and FRC curves)

    The report is written to `report.tex` inside the specified
    output directory.

    Parameters
    ----------
    snr_reports : dict[float, EvaluationReport]
        Dict mapping every SNR level to its EvaluationReport of results.
    output_path : Path
        Directory where the LaTeX report should be written.
    cfg: dict[str, Any]
        Experiment configuration dict.
    plot_options: dict[str, Any]
        Dict containing the following keyword arguments for the figure generation:
            - max_subplots: int
            - density: bool
            - dpi: int
    """
    output_path.mkdir(parents=True, exist_ok=True)

    report_path = output_path / "report.tex"
    figures_path = output_path / "figures"

    # Preamble: document class, packages and setup
    report_preamble = generate_document_preamble()

    # Classification section: recall, precision, etc.
    class_section = generate_classification_section(
        snr_reports=snr_reports,
        output_path=output_path,
        figures_path=figures_path,
        dpi=plot_options["dpi"],
    )

    # Reconstruction section: rmse, correlation, resolution
    reconstruction_section = generate_reconstruction_section(
        snr_reports=snr_reports,
        output_path=output_path,
        figures_path=figures_path,
        dpi=plot_options["dpi"],
    )

    # Save figures and generate the plots section
    plots_section = generate_plots_section(
        snr_reports=snr_reports,
        output_path=output_path,
        figures_path=figures_path,
        plot_options=plot_options,
    )

    # Write all the contents to the file
    with report_path.open("w") as f:
        f.write(report_preamble)

        f.write("\n\\begin{document}\n")

        f.write(write_experiment_info(cfg, snr_list=snr_reports.keys()))

        f.write(class_section)

        f.write(reconstruction_section)

        f.write(plots_section)

        f.write("\n\n\\end{document}")
