from pathlib import Path
from typing import Any

import pandas as pd

from method_comparison.domain.enums import Space, AggregationStrategy
from method_comparison.domain.reports import EvaluationReport
from method_comparison.visualization.plotting import AVERAGE_NAME, save_report_figures

# Required LaTeX packages for rendering tables and formatting the document.
LATEX_PACKAGES = ["booktabs", "float", "caption"]

# Human-readable names for classification metrics.
CLASSIFICATION_METRIC_NAMES = {
    "ap": "AP",
    "soft_precision": "SP",
    "soft_recall_huang_tagare": "SR (HT)",
    "soft_recall_inlier_avg": "SR (IA)",
    "soft_recall_global_avg": "SR (GA)",
}

# Human-readable names for reconstruction metrics.
RECONSTRUCTION_METRIC_NAMES = {
    "rmse": "RMSE",
    "pearson_corr": "Correlation",
    "fsc_resolution": "Resolution",
}


def generate_document_preamble() -> str:
    """
    Generate the LaTeX preamble required for the report.

    The generated preamble includes:
    - Document class declaration
    - Required LaTeX packages
    - Page geometry configuration
    - Table caption positioning

    Returns
    -------
    str
        LaTeX preamble string.
    """
    s = "\\documentclass{article}\n\n"

    # Add all necessary packages
    for package in LATEX_PACKAGES:
        s += f"\\usepackage{{{package}}}\n"

    # Configure page geometry (margin)
    s += "\\usepackage[margin=3cm]{geometry}\n"

    # Configure table captions to appear below tables.
    s += "\n\\captionsetup[table]{position=bottom}\n"

    return s


def format_column_name(name: str) -> str:
    """
    Convert internal dataframe column names into presentation-friendly labels.

    Known metric names are mapped to predefined abbreviations or labels.
    Unknown names are converted by capitalizing and replacing underscores
    with spaces.

    Parameters
    ----------
    name : str
        Original dataframe column name.

    Returns
    -------
    str
        Formatted column name suitable for display in LaTeX tables.
    """
    if name in CLASSIFICATION_METRIC_NAMES:
        return CLASSIFICATION_METRIC_NAMES[name]

    if name in RECONSTRUCTION_METRIC_NAMES:
        return RECONSTRUCTION_METRIC_NAMES[name]

    return name.capitalize().replace("_", " ")


def move_caption_to_bottom(latex: str, caption: str) -> str:
    """
    Move a LaTeX table caption below the tabular environment.

    Pandas generates captions above tables by default. This helper
    relocates the caption to the bottom of the table environment.

    Parameters
    ----------
    latex : str
        LaTeX table string generated by pandas.
    caption : str
        Caption text used in the table.

    Returns
    -------
    str
        Modified LaTeX table with the caption below the tabular block.
    """
    caption_text = f"\\caption{{{caption}}}"

    # Remove the original caption.
    latex = latex.replace(caption_text, "")

    # Reinsert the caption after the tabular environment.
    latex = latex.replace("\\end{tabular}", "\\end{tabular}\n" + caption_text)

    return latex


def format_dataframe(
    df: pd.DataFrame,
    caption: str | None = None,
    label: str | None = None,
    float_precision: int = 3,
) -> str:
    """
    Convert a dataframe into a formatted LaTeX table.

    The formatting process includes:
    - Renaming columns into presentation-friendly labels
    - Replacing underscores with spaces in string columns
    - Hiding the dataframe index
    - Formatting floating-point precision
    - Centering the table
    - Optionally adding captions and labels

    Parameters
    ----------
    df : pd.DataFrame
        Input dataframe.
    caption : str | None, optional
        Table caption.
    label : str | None, optional
        LaTeX label used for references.
    float_precision : int, optional
        Number of decimal places for floating-point values.

    Returns
    -------
    str
        Formatted LaTeX table string.
    """
    # Rename columns into display-friendly labels.
    formatted_df = df.rename(columns=format_column_name).copy()

    # Replace underscores with spaces in string-valued columns.
    string_columns = formatted_df.select_dtypes(include=["object", "string"]).columns

    formatted_df[string_columns] = formatted_df[string_columns].apply(
        lambda col: col.str.replace("_", " ", regex=False)
    )

    # Create a Styler object for LaTeX rendering.
    styler = formatted_df.style.hide(axis="index").format(precision=float_precision)

    latex = styler.to_latex(
        hrules=True,
        position="H",
        position_float="centering",
        caption=caption,
        label=label,
    )

    # Pandas emits captions above tables by default.
    # Move them below the table if requested.
    if caption:
        latex = move_caption_to_bottom(latex, caption)

    return latex


def generate_reconstruction_section(report: EvaluationReport) -> str:
    """
    Generate the reconstruction metrics section of the report.

    Parameters
    ----------
    report : EvaluationReport
        Evaluation report containing reconstruction metrics.

    Returns
    -------
    str
        LaTeX-formatted reconstruction metrics table.
    """
    reconstruction_df = report.reconstruction_metrics_dataframe()

    text = "\n\\section{Reconstruction metrics}\n\n"

    return text + format_dataframe(
        reconstruction_df,
        caption="Reconstruction metrics for each method",
    )


def generate_classification_section(report: EvaluationReport) -> str:
    """
    Generate the classification metrics section of the report.

    Tables are grouped by:
    - reconstruction space
    - aggregation strategy

    Empty groups and groups containing only the baseline average
    method are skipped.

    Parameters
    ----------
    report : EvaluationReport
        Evaluation report containing classification metrics.

    Returns
    -------
    str
        LaTeX-formatted classification section.
    """
    classification_df = report.classification_metrics_dataframe()

    text = "\n\\section{Classification metrics}\n\n"

    for space in Space:
        space_rows = classification_df["space"] == space.name

        if not space_rows.any():
            continue

        space_df = classification_df[space_rows]

        # Skip sections containing only the baseline average method.
        if len(space_df.index) == 1 and space_df["method"].iloc[0] == AVERAGE_NAME:
            continue

        text += f"\n\\subsection{{{space.label}}}\n"

        for strategy in AggregationStrategy:
            rows = space_df["aggregation_strategy"] == strategy.value

            if not rows.any():
                continue

            text += f"\n\\textbf{{{strategy.label}}}\n\n" "\\smallskip\n\n"

            # Remove grouping columns before rendering the table.
            df = space_df[rows].drop(
                ["space", "aggregation_strategy"],
                axis=1,
            )

            text += format_dataframe(df)

    return text


def generate_figures_section(figure_paths: list[Path], caption_prefix: str) -> str:
    """Generate a LaTeX block embedding a list of figures.

    Parameters
    ----------
    figure_paths : list[Path]
        Paths to the figure files to include.
    caption_prefix : str
        Prefix used in each figure caption, e.g. `"Weight distribution"`.

    Returns
    -------
    str
        LaTeX string containing one `figure` environment per path.
    """
    text = ""

    for i, path in enumerate(figure_paths, start=1):
        text += (
            f"\n\\begin{{figure}}[H]\n"
            f"  \\centering\n"
            f"  \\includegraphics[width=\\textwidth]{{{path.as_posix()}}}\n"
            f"  \\caption{{{caption_prefix} {i}}}\n"
            f"\\end{{figure}}\n"
        )

    return text


def generate_plots_section(saved_figures: dict[str, list[Path]], output_path: Path) -> str:
    """Generate a complete LaTeX plots section from saved figure paths.

    Parameters
    ----------
    saved_figures : dict[str, list[Path]]
        Mapping returned by `save_report_figures`, with keys
        `"weight_distributions"` and `"fsc_curves"`.
    output_path: Path
        Path to the directory that contains the `report.tex` file.

    Returns
    -------
    str
        LaTeX section string ready to be written into a document.
    """
    text = "\n\\section{Diagnostic Plots}\n"

    weight_paths = [p.relative_to(output_path) for p in saved_figures.get("weight_distributions", [])]
    if weight_paths:
        text += "\n\\subsection{Weight Distributions}\n"
        text += generate_figures_section(weight_paths, "Weight distribution")

    fsc_paths = [p.relative_to(output_path) for p in saved_figures.get("fsc_curves", [])]
    if fsc_paths:
        text += "\n\\subsection{FSC Curves}\n"
        text += generate_figures_section(fsc_paths, "FSC curves")

    return text


def generate_latex_report(
    report: EvaluationReport,
    output_path: Path,
    plot_options: dict[str, Any],
) -> None:
    """
    Generate a complete LaTeX report document.

    The generated report contains:
    - classification metrics section
    - reconstruction metrics section
    - fully formatted LaTeX tables

    The report is written to `report.tex` inside the specified
    output directory.

    Parameters
    ----------
    report : EvaluationReport
        Evaluation report containing all metrics.
    output_path : Path
        Directory where the LaTeX report should be written.
    plot_options: dict[str, Any]
        Dict containing the follwing keyword arguments for the figure generation:
            - max_subplots: int
            - density: bool
            - dpi: int
    """
    output_path.mkdir(parents=True, exist_ok=True)

    report_path = output_path / "report.tex"

    report_preamble = generate_document_preamble()

    classification_section = generate_classification_section(report)

    reconstruction_section = generate_reconstruction_section(report)

    # Save figures and generate the plots section
    figures_path = output_path / "figures"
    saved_figures = save_report_figures(report, figures_path, **plot_options)
    plots_section = generate_plots_section(saved_figures, output_path)

    with report_path.open("w") as f:
        f.write(report_preamble)

        f.write("\n\\begin{document}\n")

        f.write(classification_section)

        f.write(reconstruction_section)

        f.write(plots_section)

        f.write("\n\n\\end{document}")
